version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: menu_admin
      POSTGRES_PASSWORD: menu_admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
